<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>2bbffb69-11d8-4f7b-9e66-ec73d091f630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SIvCob']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SIvCob > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;English&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d35c20c3-6404-46ea-bee4-16428cebe2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com.vn/setprefs?sig=0_UVaU_5zNDEAU6ZS5WJdIzqi1Kjo%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjfu6Haq7yGAxXY5TQHHWiyIXUQ2ZgBCBU</value>
      <webElementGuid>e137905f-ac7c-4d9a-b394-7c1cf6379148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>d26840f2-5fcd-4eec-8b5e-cc328a02abc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SIvCob&quot;)/a[1]</value>
      <webElementGuid>c4a831f1-ce3f-4bb9-9971-6774cc596faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SIvCob']/a</value>
      <webElementGuid>ec4a6ff2-fad1-443c-a58f-3360c8ef5b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>97b378de-6ba7-4687-9138-c672d715e37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Báo cáo các gợi ý không phù hợp'])[1]/following::a[1]</value>
      <webElementGuid>804b0542-20c7-4039-8dc0-bb2436faf9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Français'])[1]/preceding::a[1]</value>
      <webElementGuid>757c6631-3ac9-4e70-ba4d-b6213e5efdbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='繁體中文'])[1]/preceding::a[2]</value>
      <webElementGuid>806e59c4-b80c-4f92-9238-515e414967cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>557a2bd8-b71f-47fb-b4f2-b9a63e1d453c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com.vn/setprefs?sig=0_UVaU_5zNDEAU6ZS5WJdIzqi1Kjo%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjfu6Haq7yGAxXY5TQHHWiyIXUQ2ZgBCBU')]</value>
      <webElementGuid>761ef1fd-4532-4136-acef-b8c0abe290d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>2eb80251-a551-43b4-b4a7-fa33a13004e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com.vn/setprefs?sig=0_UVaU_5zNDEAU6ZS5WJdIzqi1Kjo%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwjfu6Haq7yGAxXY5TQHHWiyIXUQ2ZgBCBU' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>02ad60c7-2682-4aa3-9f98-71252ca462b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
