<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xe</name>
   <tag></tag>
   <elementGuidId>6eea2353-cc42-4923-9c2f-d27deb440746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Xe&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div/div/div[2]/div[2]/div/ul/li[7]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>ul >> internal:has-text=&quot;MobileTin ICTInternetKhám pháXem - Mua - LuônXeApps-GameĐồ chơi số&quot;i >> internal:attr=[title=&quot;Xe&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33fa7c1c-7324-4df0-b2fd-1197764a77d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/xe.chn</value>
      <webElementGuid>f9865a69-4b4d-43de-a2d8-9d416855c02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Xe</value>
      <webElementGuid>fe2d70b1-e30e-434f-a49e-ea840636ebab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xe</value>
      <webElementGuid>7ffbcb58-63fc-429d-8283-1f95d5d00bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;genk-wrapper category&quot;]/div[@class=&quot;genk-header-wrapper&quot;]/div[@class=&quot;ghw-bottom-header&quot;]/div[@class=&quot;ghw-nav-header&quot;]/div[@class=&quot;w1040 w1160 clearfix&quot;]/ul[@class=&quot;gbh-menu-list&quot;]/li[@class=&quot;gmli&quot;]/a[1]</value>
      <webElementGuid>06a38ace-6621-4854-80d5-9902dfd9222f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div/div[2]/div[2]/div/ul/li[7]/a</value>
      <webElementGuid>c62cf8ff-187e-4b9b-85f9-706ab21ab2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Xe')])[2]</value>
      <webElementGuid>b38a9309-378f-4810-81b5-5c75f48b254b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem - Mua - Luôn'])[1]/following::a[1]</value>
      <webElementGuid>2e1ba2e1-77e6-4fc0-8ed9-39932ec8519d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khám phá'])[1]/following::a[2]</value>
      <webElementGuid>cee0f54a-ad4d-44bf-886a-db07275b2a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps-Game'])[1]/preceding::a[1]</value>
      <webElementGuid>3d4b2bf6-a876-4175-95fe-84561aab575d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đồ chơi số'])[1]/preceding::a[2]</value>
      <webElementGuid>147de9ce-9d6d-421b-ab88-241a7e3006ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xe']/parent::*</value>
      <webElementGuid>0a7450bd-7400-4bbe-a3b8-3a0d53d09558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/xe.chn')]</value>
      <webElementGuid>ee823162-57f4-474c-8095-e0324e6a920f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>bf8a0283-66d0-48b0-b399-ae5d0603eae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/xe.chn' and @title = 'Xe' and (text() = 'Xe' or . = 'Xe')]</value>
      <webElementGuid>318755ff-1014-4050-accf-fbbc3083d7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
