<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_eSPORTS</name>
   <tag></tag>
   <elementGuidId>58bac4ca-8f89-4983-a08b-f75a2a8cef71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;eSPORT&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='admWrapsite']/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;eSPORTS&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24bba37b-aa4b-4ba9-8ec6-6fa0a5589716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>eSPORT</value>
      <webElementGuid>8ecb884e-0894-46f4-aae6-2800497fb7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/esport.chn</value>
      <webElementGuid>234de273-2fe3-4303-81cd-1ef7f9d1e4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eSPORTS</value>
      <webElementGuid>ba6b7c8f-f04f-4656-be5b-07d4b3fa0ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admWrapsite&quot;)/div[@class=&quot;wp1000 wfull&quot;]/div[@class=&quot;wp1000&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;menu&quot;]/ul[1]/li[@class=&quot;normal&quot;]/a[1]</value>
      <webElementGuid>cf2c76de-109b-4e8e-9e41-b58082288de0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>73abe34a-ee1b-40f9-9d8b-2b0253627a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'eSPORTS')]</value>
      <webElementGuid>96fb083f-59e3-4efb-9a2f-176b1ad506e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GAME MOBILE'])[1]/following::a[1]</value>
      <webElementGuid>7674529f-452e-45f1-94e9-d995afe3563a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KHÁM PHÁ'])[1]/preceding::a[1]</value>
      <webElementGuid>348c50ba-0309-4582-898c-33a1f6ee316e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANGA/FILM'])[1]/preceding::a[2]</value>
      <webElementGuid>3847dc35-91f4-409c-9161-dfe3843fe988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='eSPORTS']/parent::*</value>
      <webElementGuid>8948d8b3-ac4d-4f36-9b26-02d5b376c92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/esport.chn')]</value>
      <webElementGuid>88594139-2f0e-40a7-8d63-00ee8d24d0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>71670189-3894-4977-bcb9-4069407a7b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'eSPORT' and @href = '/esport.chn' and (text() = 'eSPORTS' or . = 'eSPORTS')]</value>
      <webElementGuid>18c90e88-1bae-4e46-96a2-232577c83d18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
