<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__folder-1505891501828</name>
   <tag></tag>
   <elementGuidId>aee940df-8013-4d0c-a1bc-307941893c3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#folder-1505891501828</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='folder-1505891501828']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#folder-1505891501828 >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>639fe674-4805-4c4a-a3a6-88945001fb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folder-1505891501828</value>
      <webElementGuid>a21fdfca-2ca4-47bb-a5ed-f67eb8ebc659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ins-hello-bar-element-container ins-moveable-container ins-moveable-managed-visibility ins-element-content ins-button-display-none ins-element-link</value>
      <webElementGuid>6cef2535-1bd6-4eee-a571-51070e423f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element-name</name>
      <type>Main</type>
      <value>Message 1</value>
      <webElementGuid>35cd6d4b-6785-4148-9102-a67b2b518e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-override-name</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eca91528-5e6e-4632-93df-521af16e1589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-apply-to-all</name>
      <type>Main</type>
      <value>folder</value>
      <webElementGuid>8b30c1ad-fed0-42aa-8616-60f3f4136083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recommended-image-size</name>
      <type>Main</type>
      <value>1080x50</value>
      <webElementGuid>6920e51b-29d6-4a8a-a9dd-f28dbb33f928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>https://fptshop.com.vn/smartwatch/amazfit-balance</value>
      <webElementGuid>d62c8a38-cf4b-438d-ae86-734eac37c129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-background-color-changed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>427c9948-bcbb-4e2d-b3c9-eac0d99b5ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-blank</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b0be8dad-eb7b-44d4-8b75-a7377097430e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ins-hello-bar&quot;)/div[@class=&quot;ins-slider-container vertical ins-moveable-managed-overflow ins-overflow-hidden&quot;]/div[@id=&quot;ins-wrap1531840524000&quot;]/div[@id=&quot;folder-1505891501828&quot;]</value>
      <webElementGuid>6cc659f0-7f35-4847-b440-565f45e3f437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='folder-1505891501828']</value>
      <webElementGuid>a94924c6-793c-4140-8f31-9f8c71964a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ins-wrap1531840524000']/div</value>
      <webElementGuid>382a299a-9ae5-40dc-8f64-16d3100a8d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[3]</value>
      <webElementGuid>9d88b45b-d01b-49e7-9e49-3f5f05819a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::div[10]</value>
      <webElementGuid>5399bc18-4982-4aef-abf5-4aac04e07f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin hay'])[1]/preceding::div[24]</value>
      <webElementGuid>2277a172-9c6e-486c-9594-819c2bc25309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>3d9191bb-2e67-4abf-bcfd-5bacc53f230d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'folder-1505891501828']</value>
      <webElementGuid>cfb218b6-82a8-4856-b729-b9575771ca9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
