<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp tn in thoi, my tnh, ph kin. cn tm_key</name>
   <tag></tag>
   <elementGuidId>490490e3-9480-4721-bf1c-9511b557741a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nhập tên điện thoại, máy tính, phụ kiện... cần tìm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e81a4b4c-236f-4362-b162-96ddecfd0dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-stxt</value>
      <webElementGuid>9809cbf6-f5c3-44df-944e-6a91d5f65b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c22d50c3-4097-42f8-bde4-2e036fbd65ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>3e690666-b319-478f-a9b1-3caba7af8a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên điện thoại, máy tính, phụ kiện... cần tìm</value>
      <webElementGuid>d61574bb-6c49-4f16-9020-4204fe004803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fcc8be9d-7c01-4733-9777-99b60e684a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f0642b8e-ba9e-4b94-97b2-73494fefd8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;key&quot;)</value>
      <webElementGuid>63f0d9bc-c9ea-4860-9b29-9fb598086f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='key']</value>
      <webElementGuid>750c2dac-6329-434b-add2-8c84c6bb219a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7239c68c-6de7-4b1b-bfd2-4f73848b3a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'key' and @placeholder = 'Nhập tên điện thoại, máy tính, phụ kiện... cần tìm']</value>
      <webElementGuid>553fe431-ade8-4492-83a5-beacf2eba729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
