<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ng nhp_callout</name>
   <tag></tag>
   <elementGuidId>84858382-aea4-493f-9f0d-b0a5257d0314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='callout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e516a4bc-d9e1-41af-bc22-8813456d10fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>59c66493-20f3-44bf-97a9-193171be6d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>942f5109-a7ef-40d4-9315-45cb904fcb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5604312b-3dc2-47c1-b978-0f48d36e20b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callout</value>
      <webElementGuid>5f26d40c-88d6-441e-b9aa-d3e457a218fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ogs.google.com.vn/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=aaf101342224689f&amp;cce=1&amp;dc=1&amp;gm3=1&amp;origin=https%3A%2F%2Fwww.google.com.vn&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=vi</value>
      <webElementGuid>b9610801-83ac-4729-9a05-1ca24844b06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_Dd gb_gb gb_rd&quot;]/div[3]/iframe[1]</value>
      <webElementGuid>db83478d-d751-4f45-a8df-081bd53a01f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='callout']</value>
      <webElementGuid>1aaf7930-44bd-4b31-ae16-827f6b05735f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div[3]/iframe</value>
      <webElementGuid>f4b80ab8-56e2-4ab7-b3b4-28e909cc0c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>50c6ae71-a270-44be-aa85-067a63084466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'callout' and @src = 'https://ogs.google.com.vn/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=aaf101342224689f&amp;cce=1&amp;dc=1&amp;gm3=1&amp;origin=https%3A%2F%2Fwww.google.com.vn&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=vi']</value>
      <webElementGuid>39ee071b-2a0a-4334-910b-4262fdd90f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'callout' and @src = 'https://ogs.google.com.vn/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=aaf101342224689f&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Fwww.google.com.vn&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=vi']</value>
      <webElementGuid>0a41ce1e-14b4-49ec-aa91-a3ea1d9a8700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
