<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1234567890-</name>
   <tag></tag>
   <elementGuidId>74e502f6-9f10-45e4-8aea-b5c5d1d0c96a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kbd']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kbd > div:nth-of-type(2) > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;`1234567890-=&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38158e57-0e60-4372-bcdf-0d400b96c245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>`1234567890-=</value>
      <webElementGuid>1dde4e99-328e-4018-aefd-8fcd63a000fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kbd&quot;)/div[2]/div[1]</value>
      <webElementGuid>3288733b-325f-4c5e-9e3c-1a34ba84bb5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kbd']/div[2]/div</value>
      <webElementGuid>0824e293-69ea-4b82-8bfa-0380447b0c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếng Việt Telex'])[1]/following::div[5]</value>
      <webElementGuid>f7a01e2c-7a20-4795-bc5d-35f2f18d948b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div</value>
      <webElementGuid>a4b12fe3-6519-48ae-8b16-eb3434daf6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '`1234567890-=' or . = '`1234567890-=')]</value>
      <webElementGuid>9efd3661-94c5-47ea-954c-4f9e61500241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
