<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_zxcvbnm,</name>
   <tag></tag>
   <elementGuidId>3ec9e824-315a-458a-acc8-e4b06cc473db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kbd']/div[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kbd > div:nth-of-type(2) > div:nth-of-type(4)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;zxcvbnm,./&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9a0f6c2-898c-4517-bf69-d027f96ea59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>zxcvbnm,./</value>
      <webElementGuid>d7e438ba-8f82-49f4-b8fd-5bb11ae7e9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kbd&quot;)/div[2]/div[4]</value>
      <webElementGuid>b7dece74-5138-4606-973d-584eeffe9189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kbd']/div[2]/div[4]</value>
      <webElementGuid>a8b98230-b1b7-4d0d-9ce7-bba6dab5a3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=';'])[1]/following::div[1]</value>
      <webElementGuid>e5631a35-8f61-4652-ba74-0e75c27d49b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[4]</value>
      <webElementGuid>55ab2039-506c-4cfd-bfaf-1743fa009bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'zxcvbnm,./' or . = 'zxcvbnm,./')]</value>
      <webElementGuid>25a56a76-66cf-4d69-bc7d-82f50d03332f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
