<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobile</name>
   <tag></tag>
   <elementGuidId>feab6bcd-54fe-465f-b729-c5213dee4dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.submenu-expand-item.cate > a[title=&quot;mobile&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-expand']/div/div/ul/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-expand >> internal:role=link[name=&quot;Mobile&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d92c8c72-5007-4a3e-9ba5-c297bd3aff9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mobile.chn</value>
      <webElementGuid>abb51c7d-e84c-43b2-a7df-95736a2bfeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>f3c9e2c5-29b1-4f22-ae44-bbbc2ab9cedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobile</value>
      <webElementGuid>aa00b205-070f-4b24-86bd-6e3e10b2fee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-expand&quot;)/div[@class=&quot;clearfix menu-clear&quot;]/div[@class=&quot;w1040 clearfix&quot;]/ul[@class=&quot;menu-expand-list&quot;]/li[@class=&quot;menu-expand-item&quot;]/ul[@class=&quot;submenu-expand-list&quot;]/li[@class=&quot;submenu-expand-item cate&quot;]/a[1]</value>
      <webElementGuid>a47ef447-3857-482c-acf5-bf062354adb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-expand']/div/div/ul/li/ul/li/a</value>
      <webElementGuid>2c3366b1-4ab8-4946-8ef5-9364106d73e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Mobile')])[2]</value>
      <webElementGuid>86399cc9-05ee-4da3-bbc7-cf3499493f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đồ chơi số'])[1]/following::a[2]</value>
      <webElementGuid>8c152c6a-292a-4c2d-b1cb-cea65473712a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps-Game'])[1]/following::a[3]</value>
      <webElementGuid>4a0a6499-0459-4422-a47d-e1e0ffaae418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điện thoại'])[1]/preceding::a[1]</value>
      <webElementGuid>c16a226e-9850-48ce-b6b1-3ebc9da6cb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máy tính bảng'])[1]/preceding::a[2]</value>
      <webElementGuid>934d4f99-68e1-4271-950b-575e858ee0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/mobile.chn')])[2]</value>
      <webElementGuid>d660a36b-5e1f-4d83-8cd1-ab461cc0e5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>42c6f031-8959-4c54-96db-14e459db971f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mobile.chn' and @title = 'mobile' and (text() = 'Mobile' or . = 'Mobile')]</value>
      <webElementGuid>935365e1-3ecb-4970-98c5-8422788b2be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
