<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hc lm AI_searchinput</name>
   <tag></tag>
   <elementGuidId>f844f4f7-fda3-4a69-bc12-1cf5e21ba49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchinput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='searchinput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;h&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>955c22e8-ab33-49d2-ba6c-b0e50abef5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchinput</value>
      <webElementGuid>791bfc66-3603-4286-8f94-1b315427a4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a00bedf-2552-4ad5-a65a-ad5f74fa8657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return BBEnterPress1(event)</value>
      <webElementGuid>9c2f9f17-b7e7-4132-a755-a655254013e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Nhập nội dung tìm kiếm ...</value>
      <webElementGuid>6273380d-46fe-4247-902e-5433e383134b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchinput&quot;)</value>
      <webElementGuid>fe462d92-d193-4933-bb40-d072644f6b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='searchinput']</value>
      <webElementGuid>8f982c9a-a3b4-43e7-b92d-e0df5161f77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div/div[2]/div/div[2]/p</value>
      <webElementGuid>e7d70c5b-6224-4c11-9791-c1c7a14d2603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Học làm AI'])[1]/following::p[1]</value>
      <webElementGuid>c35f9013-86cf-4a51-88d6-93aee7ce4b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Year New Choice'])[1]/following::p[1]</value>
      <webElementGuid>52dff258-05dd-4898-92f2-a2ed77c66b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[1]/preceding::p[1]</value>
      <webElementGuid>bfe755a3-9f51-410c-8504-16ff5fff3a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tin ICT'])[1]/preceding::p[1]</value>
      <webElementGuid>0283b2e2-3559-47c9-bb7b-4f7a36055fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='h']/parent::*</value>
      <webElementGuid>14a06876-6d8e-43e6-a17d-0d527a062cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>f44c2a93-8e17-444f-b324-c813fa642e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'searchinput']</value>
      <webElementGuid>26cfcc6d-573c-4ccc-9aa9-ca593d1e4eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
