<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_20242023202220212020</name>
   <tag></tag>
   <elementGuidId>d7247c03-3ee2-4fd8-b81c-3a1f69608bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ksclivbdf-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ksclivbdf-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;year&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59c15c73-c013-4b3d-a30a-e089d484fbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ksclivbdf-year</value>
      <webElementGuid>27a38e89-06e8-495c-99c9-fa3cadd33e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>e36fe402-9877-44bb-a6af-0a569d6fb29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dkcacheid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>baf67b08-59b3-40c1-ad4e-d6bda592b3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20242023202220212020</value>
      <webElementGuid>44c946c7-f914-4931-85cf-47132c17a958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ksclivbdf-year&quot;)</value>
      <webElementGuid>4a633a00-1c4e-4a38-a5d6-e6b929e29929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ksclivbdf-year']</value>
      <webElementGuid>d71d8d93-3a8a-47e8-a300-81b24db99412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div[2]/div/div/div/div[3]/div[2]/div/div/span/div/ul/li[3]/select</value>
      <webElementGuid>3ad795a8-ffb3-4bf8-8fc2-5a4b525fdb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tháng 12'])[1]/following::select[2]</value>
      <webElementGuid>87d19851-7cbd-426f-b0d3-77c87fc773a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tháng 11'])[1]/following::select[2]</value>
      <webElementGuid>5ec10543-8d10-4fb9-b432-aac06cd1141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem'])[1]/preceding::select[1]</value>
      <webElementGuid>4d59bc3c-8757-4b24-9c2a-936967722d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rò rỉ ảnh iPhone 16 Pro, Pixel 9 Pro cho thấy Apple, Google cần công nghệ camera của Huawei'])[1]/preceding::select[1]</value>
      <webElementGuid>6cc810ae-6158-4e1e-9190-c612de4aeddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/select</value>
      <webElementGuid>c66c4d9a-c83c-4708-9a3b-dd5f3e12fdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ksclivbdf-year' and (text() = '20242023202220212020' or . = '20242023202220212020')]</value>
      <webElementGuid>efc80b26-2054-46b7-8dd8-2c5494dcebf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
