<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Ngy123456789101112131415161718192021_8e03e4</name>
   <tag></tag>
   <elementGuidId>55026a8d-3101-40f1-8a3a-7b9c694a9eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ksclivbdf-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ksclivbdf-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;day&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>25ff63a7-b1f5-4e00-8103-78012fff4d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ksclivbdf-date</value>
      <webElementGuid>794a3904-05a4-4e97-9469-7ce8bf033dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>4d9140e4-6eae-42f6-ae59-bf93239cee95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dkcacheid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>625817b9-939a-422b-8917-2f54d7775672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngày12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>739a7b63-956c-444b-86cf-ead9f0091098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ksclivbdf-date&quot;)</value>
      <webElementGuid>82e1ace5-28d0-42e3-941c-ef1ccb5ed47c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ksclivbdf-date']</value>
      <webElementGuid>46fa974a-cfef-428d-bbd2-b12b85b4bc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div[2]/div/div/div/div[3]/div[2]/div/div/span/div/ul/li/select</value>
      <webElementGuid>95a21023-6f6c-4541-b8e7-9f2125bcedc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày'])[1]/following::select[1]</value>
      <webElementGuid>4e2666fd-9ad0-4777-99c8-edbcafdeedca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem theo ngày'])[1]/following::select[1]</value>
      <webElementGuid>4720aab9-444d-4bba-a1d9-873a6fd46be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tháng'])[1]/preceding::select[1]</value>
      <webElementGuid>e00904ab-99ec-42e6-9273-0130257973c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tháng'])[2]/preceding::select[1]</value>
      <webElementGuid>f4935dc4-eee4-47c2-a40a-8359bcb0056c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c1ef7a37-3e5e-4f8e-b8cb-93520b206717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ksclivbdf-date' and (text() = 'Ngày12345678910111213141516171819202122232425262728293031' or . = 'Ngày12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>6cfb70f0-af9c-4df1-b27d-98e6bdf953ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
