<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ThngThng 1Thng 2Thng 3Thng 4Thng 5Th_e54b33</name>
   <tag></tag>
   <elementGuidId>f284050a-a0fb-4b92-b36e-4cca0c984482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ksclivbdf-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ksclivbdf-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;month&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1023d77f-7d62-4899-af2e-cb7dbf191b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ksclivbdf-month</value>
      <webElementGuid>0e9be6b0-82bb-48d2-ac68-f2017b22f0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>d4d14053-df4e-4de5-995b-9b50ac2ec3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dkcacheid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>79c93d3e-a1fc-4bd7-a3ae-3ee3f2ae2b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ThángTháng 1Tháng 2Tháng 3Tháng 4Tháng 5Tháng 6Tháng 7Tháng 8Tháng 9Tháng 10Tháng 11Tháng 12</value>
      <webElementGuid>5d4fc025-7119-431d-b5cd-71dac03ecc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ksclivbdf-month&quot;)</value>
      <webElementGuid>6836d941-0174-482e-8dd2-580661f59485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ksclivbdf-month']</value>
      <webElementGuid>2b94bea8-ea81-4bbd-9546-13c15ab5a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='admWrapsite']/div/div[2]/div/div/div/div[3]/div[2]/div/div/span/div/ul/li[2]/select</value>
      <webElementGuid>b7431874-0ebd-4d4c-9c35-8ccf3ce7c028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tháng 12'])[1]/following::select[1]</value>
      <webElementGuid>6f9d0609-bcb2-4e7f-89c5-7fb14505ac74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tháng 11'])[1]/following::select[1]</value>
      <webElementGuid>4c57e0dd-064f-4cd4-af3a-6b530edd9487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem'])[1]/preceding::select[2]</value>
      <webElementGuid>4ec2c8f1-78e1-48b2-b09a-d5ebc91a9003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rò rỉ ảnh iPhone 16 Pro, Pixel 9 Pro cho thấy Apple, Google cần công nghệ camera của Huawei'])[1]/preceding::select[2]</value>
      <webElementGuid>fd2070e0-d5d6-4807-ad22-0f84ed7828f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/select</value>
      <webElementGuid>4bc5187d-e440-46a0-95eb-70a08606dfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ksclivbdf-month' and (text() = 'ThángTháng 1Tháng 2Tháng 3Tháng 4Tháng 5Tháng 6Tháng 7Tháng 8Tháng 9Tháng 10Tháng 11Tháng 12' or . = 'ThángTháng 1Tháng 2Tháng 3Tháng 4Tháng 5Tháng 6Tháng 7Tháng 8Tháng 9Tháng 10Tháng 11Tháng 12')]</value>
      <webElementGuid>16cbecf5-1789-4eb8-973a-19e17106c582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
