<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tm hiu thm</name>
   <tag></tag>
   <elementGuidId>8054bba7-f6b5-4a93-921a-8f554e1fdc74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-content']/section[2]/div/div[4]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.glue-button._google-io-2024-cta-button.glue-button--low-emphasis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tìm hiểu thêm&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a82806c-d65d-4fe7-ad50-ef6ed49177f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>20ca435e-0bdd-4b0b-819a-3bbc281541a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://blog.google/technology/developers/google-io-2024-collection</value>
      <webElementGuid>dbad33e1-6ea1-48b4-ab15-779fe74c6793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-cta_type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6eddcc20-6d0a-4a66-907b-3cba7fe7acd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-cta_url</name>
      <type>Main</type>
      <value>https://blog.google/technology/developers/google-io-2024-collection</value>
      <webElementGuid>3517b92a-86fc-4942-918c-af12a7d49e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-cta_text</name>
      <type>Main</type>
      <value>Tìm hiểu thêm</value>
      <webElementGuid>7938449e-e06c-4c09-8628-a68bbe1d3e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glue-button
                _google-io-2024-cta-button
                glue-button--low-emphasis
</value>
      <webElementGuid>f9154c7a-25d6-419e-a533-d9eeddad2e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-g-module_position</name>
      <type>Main</type>
      <value>1/1</value>
      <webElementGuid>05ce69eb-6f19-470c-8b72-1a72ce7923ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Tìm hiểu thêm
        </value>
      <webElementGuid>ce730cf1-27fa-4bfc-b892-3569ef8af902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/section[@class=&quot;modules-lib__dynamic_grid
    glue-page
    _google-io-2024-grid&quot;]/div[@class=&quot;glue-grid&quot;]/div[@class=&quot;glue-grid__col
          glue-grid__col--span-4-sm
          glue-grid__col--span-8-md
          glue-grid__col--span-8-lg&quot;]/div[@class=&quot;modules-lib__inline-cta
      modules-lib__inline-cta--center
      _google-io-2024-inline-cta&quot;]/a[@class=&quot;glue-button
                _google-io-2024-cta-button
                glue-button--low-emphasis&quot;]</value>
      <webElementGuid>cbb6b37a-9f2b-4979-b047-87bb8f42322b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/section[2]/div/div[4]/div[3]/a</value>
      <webElementGuid>b0a2c8de-f182-493e-8cf6-011c80e943e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tìm hiểu thêm')]</value>
      <webElementGuid>73616269-cabf-492a-af68-1b9746e842c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem thông tin cập nhật về AI cũng như tin tức và thông báo mới nhất về sản phẩm tại Google I/O'])[1]/following::a[1]</value>
      <webElementGuid>5fa6c266-a01b-4e5c-a946-0558951d0734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dễ tiếp cận cho tất cả mọi người'])[1]/following::a[1]</value>
      <webElementGuid>30bfe0b5-d53a-463e-83f5-2d74b88cf79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Làm cho cuộc sống dễ dàng hơn với một chút trợ giúp từ các sản phẩm của chúng tôi'])[1]/preceding::a[1]</value>
      <webElementGuid>32339fa1-5622-4554-8ed6-d5c00253b8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem tất cả sản phẩm của chúng tôi'])[1]/preceding::a[1]</value>
      <webElementGuid>79513585-e21e-4739-9a7e-741958b0c098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tìm hiểu thêm']/parent::*</value>
      <webElementGuid>5793f578-3281-4f3a-86a5-bf327ddc731a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://blog.google/technology/developers/google-io-2024-collection')]</value>
      <webElementGuid>ee08916d-29a7-4de2-8e08-cd2c0b482799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>9243646f-d0e3-4a3e-8ad8-325c6f51b43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://blog.google/technology/developers/google-io-2024-collection' and (text() = '
          Tìm hiểu thêm
        ' or . = '
          Tìm hiểu thêm
        ')]</value>
      <webElementGuid>7d7ca3de-a782-4f8d-aedd-654e3af8c819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
