<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tinhte</name>
   <tag></tag>
   <elementGuidId>53ff8dd4-7049-4111-b0d2-976b1856f296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.jsx-663639823.tinhte-text__name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div/div/div/a/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tinhte Mạng xã hội&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>691fc8c6-695f-4272-8a87-3c8b19695d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-663639823 tinhte-text__name</value>
      <webElementGuid>c832e4cd-7d5e-4db8-a33f-d7ca666a5721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tinhte</value>
      <webElementGuid>4ea5754a-ff43-4291-afc6-b1056c6dba7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;root&quot;]/header[@class=&quot;jsx-663639823&quot;]/div[@class=&quot;jsx-663639823 row header-wrapper&quot;]/div[@class=&quot;jsx-663639823 col-left left&quot;]/div[@class=&quot;jsx-663639823 logo&quot;]/a[@class=&quot;jsx-663639823&quot;]/div[@class=&quot;jsx-663639823 tinhte-text&quot;]/div[@class=&quot;jsx-663639823 tinhte-text__name&quot;]</value>
      <webElementGuid>2db68865-2cde-447a-9340-d61f55cc601c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div/div/div/a/div[2]/div</value>
      <webElementGuid>bea2e312-bbe9-44d6-bdf0-a6b2280f5db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mạng xã hội'])[1]/preceding::div[1]</value>
      <webElementGuid>0bb32b61-6464-41c1-b6e7-9b7afe810f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm tùy chỉnh'])[1]/preceding::div[7]</value>
      <webElementGuid>40fc6623-bfa7-40a3-abed-3c3dc9ef5b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tinhte']/parent::*</value>
      <webElementGuid>38185cc6-020d-4409-b12c-9b3317a550c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>a1d9c372-f674-44bd-b551-1758e55b0bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tinhte' or . = 'Tinhte')]</value>
      <webElementGuid>06e2689d-6e75-4626-8226-538454413c85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
