<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mng x hi_search (1)</name>
   <tag></tag>
   <elementGuidId>b006dd4d-0c10-4530-bc67-cd6d51de7877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gsc-i-id1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gsc-i-id1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tìm sản phẩm công nghệ, cộng đồng, bạn bè...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0631696-8199-41c1-9514-d17fdeb29664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5abffe60-671b-4487-92eb-f78a6831d753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ede3218-b827-4e70-b8fe-6a6f553db9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f0d16574-ad93-4cf2-b382-a233f61c478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gsc-input</value>
      <webElementGuid>dc45964b-5714-479e-a6c9-48170502d903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>755d2888-c24f-47af-8c08-ae09d8bec67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>tìm kiếm</value>
      <webElementGuid>55b5e44c-2d44-4526-ac2a-8977b4e6534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>tìm kiếm</value>
      <webElementGuid>6c92af68-116b-43eb-80fe-b7921624c228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsc-i-id1</value>
      <webElementGuid>a9ece1d9-f753-4663-8a42-18d37af23d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>0e6299db-ffc0-4cf6-8b88-cc0942bd1358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6d46b11-8ebc-4513-be6d-a1b0b42fe816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm công nghệ, cộng đồng, bạn bè...</value>
      <webElementGuid>b5d00ec5-9ecc-412a-bf45-8cbd48508995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsc-i-id1&quot;)</value>
      <webElementGuid>cf16fa69-3aef-45f0-8d68-7caa616d54f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gsc-i-id1']</value>
      <webElementGuid>fe9c3600-87e1-46a6-881a-541f0e018bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='gs_tti50']/input</value>
      <webElementGuid>25f68c31-e79c-47c1-85f2-5440ca16c96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7e557f33-d1c2-4069-9a25-c2cef2f9c644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @title = 'tìm kiếm' and @id = 'gsc-i-id1' and @placeholder = 'Tìm sản phẩm công nghệ, cộng đồng, bạn bè...']</value>
      <webElementGuid>6920047f-a7bf-407f-87e1-7feb8fa964c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
