<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mng x hi_search</name>
   <tag></tag>
   <elementGuidId>02852906-b6dd-4470-b08d-68622cd6415a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gsc-i-id1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gsc-i-id1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tìm sản phẩm công nghệ, cộng đồng, bạn bè...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db2f9ad1-165c-4e04-a737-322f1e623fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>367d241b-80bd-4d68-bb2f-039ed011d0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7831580d-6f52-4965-8606-b788aacd070d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1310aabd-f319-4e26-a6a0-2c7f64a2e5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gsc-input</value>
      <webElementGuid>4f450df1-4216-46f8-8b82-98fe501d58ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7104ecc8-c1a5-45ad-875c-3d21ef74a30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>tìm kiếm</value>
      <webElementGuid>332a8a1d-acb5-4675-8a0f-ee213562e87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>tìm kiếm</value>
      <webElementGuid>46d34f7b-38ee-421a-a197-e524e259abc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsc-i-id1</value>
      <webElementGuid>74c26f35-0435-4de2-aa2c-247deaa53df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>0e0a5d27-e3fc-4d1e-a387-75967bafb0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>91912b9f-9cad-4b9d-b747-5afa66fef8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm công nghệ, cộng đồng, bạn bè...</value>
      <webElementGuid>d8989f0c-0491-4cdd-b4ff-35d7cc2aa95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsc-i-id1&quot;)</value>
      <webElementGuid>1ba11a17-4ddf-480c-b76a-1d39fd3c9e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gsc-i-id1']</value>
      <webElementGuid>a129c22e-b8d6-4ae8-803e-c86fbe40f889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='gs_tti50']/input</value>
      <webElementGuid>6de5ea6e-fc53-4076-8cf3-ef5a09bf64de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>14c421a0-2ae1-4fbe-900b-7a40d6f00a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @title = 'tìm kiếm' and @id = 'gsc-i-id1' and @placeholder = 'Tìm sản phẩm công nghệ, cộng đồng, bạn bè...']</value>
      <webElementGuid>39cff358-77d6-41be-965b-72ba444d1229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
