<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_B n v ngi cha g cao nht th gii, c xy dng _3a22eb</name>
   <tag></tag>
   <elementGuidId>faa0ea5f-1ad0-41bc-9e45-792cb670e3a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#20240528094544805 > div.knswli-right.elp-list > h4.knswli-title > a.show-popup.visit-popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='20240528094544805']/div[2]/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a773bcbe-c278-4b9d-bdb1-b54dce127473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bi-an-ve-ngoi-chua-go-cao-nhat-the-gioi-duoc-xay-dung-cach-day-gan-1000-nam-ma-khong-can-den-mot-chiec-dinh-sat-20240528094544805.chn</value>
      <webElementGuid>c5518d1d-32e6-4192-8d88-15f0d469ffb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!</value>
      <webElementGuid>f47ff616-3f19-4570-b614-3ba9f92c0127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>20240528094544805</value>
      <webElementGuid>57725279-22cb-4eb2-b6fb-27b70c5081f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>newstype</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>afee7498-c514-4bff-99cb-125531f174c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show-popup visit-popup</value>
      <webElementGuid>a65ada83-3544-412d-8511-80c8e338647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popup-url</name>
      <type>Main</type>
      <value>/bi-an-ve-ngoi-chua-go-cao-nhat-the-gioi-duoc-xay-dung-cach-day-gan-1000-nam-ma-khong-can-den-mot-chiec-dinh-sat-20240528094544805.chn</value>
      <webElementGuid>d7f479d3-7108-409f-be42-bdd5de35affc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!</value>
      <webElementGuid>0d376fd3-76d7-4329-8948-73817d27ecb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;20240528094544805&quot;)/div[@class=&quot;knswli-right elp-list&quot;]/h4[@class=&quot;knswli-title&quot;]/a[@class=&quot;show-popup visit-popup&quot;]</value>
      <webElementGuid>5501f151-00fa-49e8-a524-e720a66960ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='20240528094544805']/div[2]/h4/a</value>
      <webElementGuid>585502ee-d7c6-4344-bfdb-06503d988cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!')]</value>
      <webElementGuid>63ebd274-7438-4229-8f43-13c79503cf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sống'])[3]/following::a[1]</value>
      <webElementGuid>4acfd98c-bac2-4940-aef5-ccc2be0a35b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Những người du mục Mông Cổ sống trong lều đi vệ sinh và tắm như thế nào?'])[1]/following::a[3]</value>
      <webElementGuid>837ba694-700a-4ac8-ad12-529d9597bf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xe'])[3]/preceding::a[2]</value>
      <webElementGuid>a33ba935-a360-4813-851b-dfdef146b3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khám phá'])[3]/preceding::a[5]</value>
      <webElementGuid>fa696ca7-5c16-4a79-9f94-cf8778b11ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!']/parent::*</value>
      <webElementGuid>2ca2072f-c229-4b37-95e7-44e6e92ea33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/bi-an-ve-ngoi-chua-go-cao-nhat-the-gioi-duoc-xay-dung-cach-day-gan-1000-nam-ma-khong-can-den-mot-chiec-dinh-sat-20240528094544805.chn')])[2]</value>
      <webElementGuid>8a6a5049-041d-42c3-bfd2-43b620c37968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/h4/a</value>
      <webElementGuid>70bdcc05-b6a6-459e-a17a-b271d022b793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/bi-an-ve-ngoi-chua-go-cao-nhat-the-gioi-duoc-xay-dung-cach-day-gan-1000-nam-ma-khong-can-den-mot-chiec-dinh-sat-20240528094544805.chn' and @title = 'Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!' and (text() = 'Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!' or . = 'Bí ẩn về ngôi chùa gỗ cao nhất thế giới, được xây dựng cách đây gần 1000 năm mà không cần đến một chiếc đinh sắt!')]</value>
      <webElementGuid>4762d7ed-05af-4daa-8bc5-8f49c124924a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
